feedbacks visibility
BUI-studies/buoy-platform pull request #22
Opened 2024-02-09 18:15 UTC by BUI-studies

2024-02-29 11:38 UTC, yakovenkoandyUA requested changes

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/components/DataTable/DataTable.tsx
> +			: undefined
Use optional call

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/components/Items/FeedbacksItem/FeedbacksItem.tsx
> +			return <></>
you can use type 'never' in default case to predict add new enums ROLES 
`const _exhaustiveRole: never = role`

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/components/Items/FeedbacksItem/FeedbacksItemMentor.tsx
> +						{feedbacksReactionsMap.impressions.find(imp => imp.value === impression)?.label ||
it is possible to write a function for cases with paragraphs so that you don't see this sausage here

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/components/Items/FeedbacksItem/FeedbacksItemStudent.tsx
> +						{feedbacksReactionsMap.impressions.find(imp => imp.value === impression)?.label ||
same comment component Mentor

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/pages/FeedbacksTable/FeedbacksTable.tsx
> +	const mappers = Object.freeze({
maybe transfer this mappers to helper file

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/pages/FeedbacksTable/FeedbacksTable.tsx
> +					role === ROLES.MENTOR
up this condition top variable before return

2024-02-29 11:38 UTC, yakovenkoandyUA commented on client/src/utils/cutString.util.ts
> +export const cutString = (str: string, maxLength: number) => {
maybe transfer to index files?

2024-03-01 18:15 UTC, BUI-studies commented on client/src/components/DataTable/DataTable.tsx
> +			: undefined
this case was intentionally made like this to prevent unnecessare handler assignment when `rowClick` haven't been passed

2024-04-05 08:00 UTC, yakovenkoandyUA requested changes

2024-04-05 08:00 UTC, yakovenkoandyUA commented on client/src/pages/FeedbacksTable/FeedbacksTable.tsx
> +	if (feedbacks.isLoading) return <span className="">Loading...</span>
maybe add human loader, than just a word

2024-04-05 08:00 UTC, yakovenkoandyUA commented on client/src/utils/index.ts
> +	if (str.length > maxLength) {
it is possible to extend the functionality so that the line does not cut off half or a third of the word, but cuts the full word and only then puts an ellipsis

2024-04-05 08:00 UTC, yakovenkoandyUA commented on server/src/controllers/homeworks.controller.ts
> +export const get = async (req: Request, res: Response): Promise<HomeworksResponse> => {
we can write this without return, only use arrow

2024-04-12 17:23 UTC, merged